-- Add missing testimonials for Guthrie Zaring and Alissa Meriwether
INSERT INTO testimonials (content, from_user, for_user, show_on_front_page, "order") VALUES
-- Guthrie Zaring testimonials
('Guthrie was amazing at finding homes and condos that fit our wants and needs. He showed us many places and always knew every detail we inquired about. He was very easy to reach and available when we needed him. His knowledge on the city and real estate was incredibly helpful and appreciated. We are so thankful we had Guthrie to help us in the journey of buying our first home!', 'A Happy Client', 'Guthrie Zaring', false, 0),
('Guthrie helped me purchase my first home and was my representation. Guthrie''s effort and diligence are first class and unrivaled regardless of the price of the property. Guthrie was very responsive and knew the different areas of the city very well. Highly recommend.', 'A Happy Client', 'Guthrie Zaring', false, 1),
('Guthrie Zaring was so attentive to details communication and making our lot purchase a wonderful experience! Would highly recommend Julie Pogue properties!', 'Betty Kregor', 'Guthrie Zaring', false, 2),
('My fiance and I went to an open house one Sunday morning. Guthrie was the selling agent. At the time, we were just browsing, we didn''t have a realtor. We left the open house not much interested in the house, not because anything Guthrie said or did. BUT. We did leave the open house agreeing when we decided to get more serious about buying a house we for sure wanted to give Guthrie a call in hopes that he would have the availability. We are SO thankful that when we finally called Guthrie that he was available to help us. He made the whole house buying process a breeze! He is VERY responsive, ALWAYS, ALWAYS on top of everything, and VERY knowledgeable about the area.', 'H. Hoffman', 'Guthrie Zaring', false, 3),
('Guthrie was my realtor when I bought my home, and I plan to use him again when I decide to move. He is fantastic to work with! Guthrie is extremely organized, responsive, knowledgeable, and accommodating. He knows the market, and was able to negotiate with the listing agent to secure my home under list price even when there were several other offers in. Considering my neighborhood, I am confident that Guthrie helped me make a sound investment and I''ll be able to get my money back when I sell. Thank you Guthrie!! You''re the best!', 'E. Likins', 'Guthrie Zaring', false, 4),
('If you are looking for a very professional, honest, and hardworking agent to help you find your new home, or sell your existing home, Guthrie Zaring is the agent to call. Guthrie Zaring will make you feel like you are part of his family, and will go above and beyond to make sure you are happy with his results. Remember Guthrie Zaring if you want to get things done in a timely manner. Guthrie Zaring''s expertise in the market is unparalleled!', 'R. Thomas', 'Guthrie Zaring', false, 5),
('Buying or selling a home can be an exciting experience for many but it can be stressful as well. My advice, avoid the stress by contracting with an expert real estate professional! My last home purchase was a stress free and totally enjoyable experience because I contracted with Guthrie Zaring. Guthrie was a consummate professional that provided impeccable service, amazing expertise, and an obvious commitment to his profession. I highly recommend Guthrie for anyone''s real estate needs, he''s an expert and provides "5 STAR" service.', 'R. Williamson', 'Guthrie Zaring', false, 6),
-- Alissa Meriwether testimonials
('Great experience, very happy with Alissa and Julie Pogue properties!', 'Weyman Willingham', 'Alissa Meriwether', false, 0),
('Alissa is amazing to work with and I would refer her to anyone considering to buy or sell. She is intelligent, professional, and responsive. I received a full offer within 24 hours of being listed!', 'Dana Orlando', 'Alissa Meriwether', false, 1),
('Thank you Website Dummy Properties and Alissa for making my dreams come true and still working behind the scenes in every capacity to knit all the tiny pieces together from home warranties to transfer of services. I couldn''t be happier that I chose your company and Alissa to work with!', 'Kimberly Davenport', 'Alissa Meriwether', false, 2),
('Professional, friendly, courteous, good follow up, thorough, and competent... Alissa is our agent of choice!', 'Aletha Marcum', 'Alissa Meriwether', false, 3),
('Alissa was absolutely wonderful to work with throughout the process of searching for and then purchasing my first home! She was so helpful kind patient and quick at getting back to me any time I reached out to her. Her knowledge of every facet of home buying put me at ease. I would recommend Alissa to anyone needing a realtor!', 'Alex Kimura', 'Alissa Meriwether', false, 4);
