CREATE TABLE IF NOT EXISTS testimonials (
    id BIGSERIAL PRIMARY KEY,
    content TEXT NOT NULL,
    from_user TEXT NOT NULL,
    for_user TEXT,
    show_on_front_page BOOLEAN NOT NULL DEFAULT false,
    "order" INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_testimonials_for_user ON testimonials (for_user);
CREATE INDEX IF NOT EXISTS idx_testimonials_show_on_front_page ON testimonials (show_on_front_page);
CREATE INDEX IF NOT EXISTS idx_testimonials_order ON testimonials ("order");

-- Migrate existing testimonials from HomePage and TeamMemberPage
-- Testimonials that appear on both pages will have both for_user and show_on_front_page set
INSERT INTO testimonials (content, from_user, for_user, show_on_front_page, "order") VALUES
-- HomePage testimonials (show_on_front_page = true)
('We can tell you from over a decade of experience that no realtor will care about you the way Julie Pogue will.', 'Brad and Karin Tyrer', 'Website Dummy', true, 0),
('In over 30 years of service, Website Dummy Properties has purchased and sold no less than 5 of our homes. Always kindly, swiftly and professionally. We have left town and left them fully in control with the process. Always 100% pleased with both our purchased and SOLD properties. No headaches no complications. A top service business and experience from beginning to end.', 'Giselle M.', 'Website Dummy', true, 1),
('Julie is an incredibly kind and knowledgeable owner with a warm personality and gracious heart. I am so grateful to have met Julie! She truly seeks to empower others and takes the time to listen to her clients. She is very accessible via phone, text, and email. So responsive. She is so driven to support her clients and staff. Professional, prompt, and sweet. Thank you Website Dummy Properties!', 'S Maddison', 'Website Dummy', true, 2),
('We love our new house! Julie was so helpful with a lot of in-depth information about different areas of town. She has been a great resource even after we moved in, connecting us with local professionals and following up about our move. Thanks Julie!', 'Victoria Mount', 'Website Dummy', true, 3),
('I''ve bought and sold five properties with Website Dummy Properties; there is no other option.', 'Brian Webb', 'Website Dummy', true, 4),
('Julie and her team are the absolute best! Their attention to detail and dedication to their clients is unmatched. They made our home selling experience stress-free and successful.', 'Anonymous', NULL, true, 5),
('Website Dummy Properties exceeded all our expectations. They found us the perfect home in our desired neighborhood and at the right price. We couldn''t be happier!', 'Happy Customer', NULL, true, 6),
('The professionalism and expertise of Julie and her team is outstanding. They guided us through every step of the process with patience and care.', 'Satisfied Buyer', NULL, true, 7),
('Working with Website Dummy Properties was a game-changer for us. Their market knowledge and negotiation skills helped us get the best deal possible.', 'Thankful Client', NULL, true, 8),
-- Additional TeamMemberPage testimonials (for_user = 'Website Dummy', show_on_front_page = false)
('Working with Website Dummy Properties was an absolute pleasure! Julie and her team went above and beyond to help us find the perfect home. Their knowledge of the market, attention to detail, and genuine care made the entire process seamless. They truly listened to our needs and worked tirelessly to ensure we found a home that fit our criteria and budget. I couldn''t be happier with my experience and highly recommend Website Dummy Properties to anyone looking for top-notch real estate professionals.', 'Nelea Abshear', 'Website Dummy', false, 0),
('We had a wonderful experience with Julie. This was my 6th home sale and this was by far the easiest sale process I''ve experienced. I was asked what our goals were and we aligned on a plan. I was asked to trust the process honed from years of experience and was rewarded. I cannot recommend this team enough!', 'Jeremy A.', 'Website Dummy', false, 1),
('Julie and her fantastic team helped us find our dream house this month! They are experts at everything in Louisville - from nuances between different neighborhoods, to market trends, to trustworthy contractors for hire during and after the sale. More importantly, they are committed to taking care of their clients in every way possible. They got us the house we wanted in a very competitive market, they were fierce advocates for us during the negotiation, and they helped us in countless ways during the move and as we settled in our new home. I have never before seen a real estate office so engaged and effective. I will definitely use them again and cannot recommend them highly enough.', 'Adam R.', 'Website Dummy', false, 2),
('Julie was a great partner in the sale of our home. She was, of course, a joy to work with, but more importantly, she had a great feel for the market and how to convert an interested prospect into a satisfied buyer.', 'Charlie Moyer', 'Website Dummy', false, 3),
('My husband and I met Julie at one of her open houses. She was easy to talk to, extremely polite, and very knowledgeable with the Louisville market area, which was important to us as we were moving in from out of state. She earned our trust and confidence quickly and didn''t disappoint throughout the entire process. You can tell that she absolutely loves what she does and enjoys working for her clients. She''s dedicated, responsive to your needs, keeps you updated throughout the entire process, makes the process easy, and also has a great staff!', 'Tara & Dusty D.', 'Website Dummy', false, 4),
('We moved at the height of the real estate market craziness last spring, when houses were going on and off the market within a day or two. We had to buy a house sight unseen from the coast of Virginia and were terrified we wouldn''t be able to find something in time to start school here this fall. Thank goodness for Julie! She kept me from panicking so many times, and remained steadfast in her confidence that we would find a fantastic home—and she was right! And when she found that house, she guided us through the negotiation process and ended up getting us a much better deal than we ever could have imagined. Now we are settled and loving our new home. I am so grateful that we had Julie with her expertise and experience on our side.', 'Becky & Jesse H.', 'Website Dummy', false, 5),
('We finally got to meet Julie Pogue...the Realtor with yard signs that are everywhere, and now we know why. Let us tell you, it is better than we could have ever dreamed. It has been an unbelievable experience working with her! Every time something came up, she knew exactly how to handle it with ease and a professional manner. We cannot thank her enough.', 'Patrick & Linda Fitzgerald', 'Website Dummy', false, 6),
('Julie is simply the best! We''ve worked with several realtors over the years and no one else has matched Julie''s dedication, professionalism or expertise. We highly recommend Website Dummy Properties for any buying or selling needs. Julie takes wonderful care of her clients!', 'Chris Lombardi', 'Website Dummy', false, 7),
('If you''re looking for a hard working force of nature who will spare no effort and pay attention to every single detail imaginable, Julie Pogue is your realtor! Her years of experience show, and her network of professionals who can help with special needs is broad and extensive. I highly recommend Julie and her excellent team for your real estate needs!', 'Jeremy Bewley', 'Website Dummy', false, 8),
('Julie was phenomenal. She guided me through what I feared would be a stressful process selling my Uncle''s home. It was not stressful at all. She helped me hire trusted people to move furniture and to clean the home, and then she got my Uncle a great price on his home in a matter of days. I would recommend Julie and her firm to anyone who wants to maximize the sales price of his or her home!', 'Janet Jakubowicz', 'Website Dummy', false, 9),
('Incredibly helpful. Always available. Made the process smooth and simple. Couldn''t have picked a better agent. Would highly recommend.', 'Michael Taylor', 'Website Dummy', false, 10),
('Julie is one of the smartest people in my acquaintance -- her knowledge and savvy about the real estate market in Louisville is unmatched. Julie''s work ethic and dedication to her clients will give you full peace of mind whether you are buying or selling a house -- or even just looking!', 'Mia Simpson Culp', 'Website Dummy', false, 11),
('Website Dummy Properties was amazing at helping my wife and I find a house in Louisville; and then going above-and-beyond in making the transaction so easy!! Everyone at Julie''s office is very knowledgeable, friendly, communicative, and helpful. Julie Pogue, Julie Hermann, and Joy Craig worked together flawlessly, and their strong dedication to ensure client satisfaction was apparent.', 'Lukas Delaney', 'Website Dummy', false, 12),
('Julie was amazing and supportive! We had a larger home to sell, but when the perfect family came along, Julie made everything simple and very straightforward. I cannot say how much we appreciated her unflagging support and care through it all. I would recommend Website Dummy Properties as the most professional and compassionate company to deal with one of your life''s most important decisions.', 'Bill and Judy Hoffmeister', 'Website Dummy', false, 13),
('I gave Julie and her team an almost impossible task and they pulled it off. She helped find a home that met our requirements within a very short time window. She was there every step of the way. The level of service is beyond exceptional and her experience is what sets Julie and her team apart from everyone else. I highly recommend Website Dummy Properties.', 'Jeff Rash', 'Website Dummy', false, 14),
('Julie came to our attention when she represented the buyer on a house we were purchasing. When we later sold that house we decided to give Julie a call. She is attentive, responsive, knowledgeable, well-connected and energetic. I marvel at her energy! She sold our house for well above asking price in a matter of days. We highly recommend Julie and her team.', 'Brian & Amanda Webb', 'Website Dummy', false, 15),
('Julie has been amazing to work with!! Moving is such a stressful process so it is comforting to know that you have someone in your corner who is looking out for your best interest. She was in constant contact with us throughout the entire process of selling our home and purchasing our new home. If there was ever any issue I could call her and she would take care of it immediately! I would highly recommend Julie! She has taken great care of us :)', 'Neil & Hillary Patil', 'Website Dummy', false, 16),
('Julie helped us so much with our move to Louisville. They made buying a house smooth and easy and went out of their way to answer our questions and help us understand the community and schools. Julie even rushed tools over late on the Saturday night that we arrived at the house and had a small plumbing problem. I would recommend Julie to anyone looking for a real estate agent especially in Anchorage.', 'Jennifer & Todd Tamburino', 'Website Dummy', false, 17),
('Julie was looking under every rock for my son to get the best deal.', 'Chris Dabbikeh', 'Website Dummy', false, 18),
('We unreservedly recommend her to all who have need of a real estate agent.', 'Larry and Brenda Boer', 'Website Dummy', false, 19),
-- Guthrie Zaring testimonials
('Guthrie was amazing at finding homes and condos that fit our wants and needs. He showed us many places and always knew every detail we inquired about. He was very easy to reach and available when we needed him. His knowledge on the city and real estate was incredibly helpful and appreciated. We are so thankful we had Guthrie to help us in the journey of buying our first home!', 'A Happy Client', 'Guthrie Zaring', false, 0),
('Guthrie helped me purchase my first home and was my representation. Guthrie''s effort and diligence are first class and unrivaled regardless of the price of the property. Guthrie was very responsive and knew the different areas of the city very well. Highly recommend.', 'A Happy Client', 'Guthrie Zaring', false, 1),
('Guthrie Zaring was so attentive to details communication and making our lot purchase a wonderful experience! Would highly recommend Julie Pogue properties!', 'Betty Kregor', 'Guthrie Zaring', false, 2),
('My fiance and I went to an open house one Sunday morning. Guthrie was the selling agent. At the time, we were just browsing, we didn''t have a realtor. We left the open house not much interested in the house, not because anything Guthrie said or did. BUT. We did leave the open house agreeing when we decided to get more serious about buying a house we for sure wanted to give Guthrie a call in hopes that he would have the availability. We are SO thankful that when we finally called Guthrie that he was available to help us. He made the whole house buying process a breeze! He is VERY responsive, ALWAYS, ALWAYS on top of everything, and VERY knowledgeable about the area.', 'H. Hoffman', 'Guthrie Zaring', false, 3),
('Guthrie was my realtor when I bought my home, and I plan to use him again when I decide to move. He is fantastic to work with! Guthrie is extremely organized, responsive, knowledgeable, and accommodating. He knows the market, and was able to negotiate with the listing agent to secure my home under list price even when there were several other offers in. Considering my neighborhood, I am confident that Guthrie helped me make a sound investment and I''ll be able to get my money back when I sell. Thank you Guthrie!! You''re the best!', 'E. Likins', 'Guthrie Zaring', false, 4),
('If you are looking for a very professional, honest, and hardworking agent to help you find your new home, or sell your existing home, Guthrie Zaring is the agent to call. Guthrie Zaring will make you feel like you are part of his family, and will go above and beyond to make sure you are happy with his results. Remember Guthrie Zaring if you want to get things done in a timely manner. Guthrie Zaring''s expertise in the market is unparalleled!', 'R. Thomas', 'Guthrie Zaring', false, 5),
('Buying or selling a home can be an exciting experience for many but it can be stressful as well. My advice, avoid the stress by contracting with an expert real estate professional! My last home purchase was a stress free and totally enjoyable experience because I contracted with Guthrie Zaring. Guthrie was a consummate professional that provided impeccable service, amazing expertise, and an obvious commitment to his profession. I highly recommend Guthrie for anyone''s real estate needs, he''s an expert and provides "5 STAR" service.', 'R. Williamson', 'Guthrie Zaring', false, 6),
-- Alissa Meriwether testimonials
('Great experience, very happy with Alissa and Julie Pogue properties!', 'Weyman Willingham', 'Alissa Meriwether', false, 0),
('Alissa is amazing to work with and I would refer her to anyone considering to buy or sell. She is intelligent, professional, and responsive. I received a full offer within 24 hours of being listed!', 'Dana Orlando', 'Alissa Meriwether', false, 1),
('Thank you Website Dummy Properties and Alissa for making my dreams come true and still working behind the scenes in every capacity to knit all the tiny pieces together from home warranties to transfer of services. I couldn''t be happier that I chose your company and Alissa to work with!', 'Kimberly Davenport', 'Alissa Meriwether', false, 2),
('Professional, friendly, courteous, good follow up, thorough, and competent... Alissa is our agent of choice!', 'Aletha Marcum', 'Alissa Meriwether', false, 3),
('Alissa was absolutely wonderful to work with throughout the process of searching for and then purchasing my first home! She was so helpful kind patient and quick at getting back to me any time I reached out to her. Her knowledge of every facet of home buying put me at ease. I would recommend Alissa to anyone needing a realtor!', 'Alex Kimura', 'Alissa Meriwether', false, 4);
